-- Create the messages table for AI Chat
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    role TEXT NOT NULL, -- 'user' or 'bot'
    content TEXT NOT NULL
);

-- Enable Row Level Security (RLS) if needed, or allow public access for testing
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Creating a policy to allow anyone to read and insert (For simplicity in this demo)
CREATE POLICY "Allow public read-write access" ON messages
    FOR ALL
    USING (true)
    WITH CHECK (true);
